### ISSUE TITLE
Strip feeder setup: Hole vision for pickup

### ISSUE THREAD

**Issue by FlyingLotus1983** [TinWhiskers/openpnp#4] opened 2015-09-25 06:17 UTC

**Comment by FlyingLotus1983** [comment] 2015-09-25 09:34
@vonnieda Is this related to #5 ?  Assuming that this is an issue for generic usage of hole finding during cut strip setup?  If so, what is the status currently?  What works, what still needs to be added?  

I do think that hole vision for pickup in general is very important so this will likely be tagged/labeled as such.

**Comment by vonnieda** [comment] 2015-09-25 15:25
This is a duplicate of #5, closing it.

**Closed by vonnieda** 2015-09-25 15:25 UTC
Labels: enhancement, Feeders/CutStrip, Vision/TopVision
